In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.4.6


In [2]:
array_1d = np.array([10, 20, 30, 40, 50])
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('1D:\n', array_1d)
print('\n2D:\n', array_2d)
print('\n3D:\n', array_3d)

1D:
 [10 20 30 40 50]

2D:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
for name, arr in [('1D', array_1d), ('2D', array_2d), ('3D', array_3d)]:
    print(f'{name}: ndim={arr.ndim}, shape={arr.shape}, size={arr.size}, dtype={arr.dtype}')

1D: ndim=1, shape=(5,), size=5, dtype=int64
2D: ndim=2, shape=(3, 3), size=9, dtype=int64
3D: ndim=3, shape=(2, 2, 2), size=8, dtype=int64


In [4]:
print('First element:', array_1d[0])
print('Last element:', array_1d[-1])
print('1D slice [1:4]:', array_1d[1:4])
print('Every second element:', array_1d[::2])
print('\n2D element [1,2]:', array_2d[1,2])
print('First row:', array_2d[0,:])
print('Second column:', array_2d[:,1])
print('Top-left 2x2:\n', array_2d[:2,:2])
print('\n3D first layer:\n', array_3d[0])

First element: 10
Last element: 50
1D slice [1:4]: [20 30 40]
Every second element: [10 30 50]

2D element [1,2]: 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2:
 [[1 2]
 [4 5]]

3D first layer:
 [[1 2]
 [3 4]]


In [5]:
numbers = np.arange(1,13)
print('Original:', numbers)
print('\n3 x 4:\n', numbers.reshape(3,4))
print('\n4 x 3:\n', numbers.reshape(4,3))

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4 x 3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
print('zeros:\n', np.zeros((2,3)))
print('\nones:\n', np.ones((2,3)))
print('\narange:', np.arange(0,10,2))
print('\nlinspace:', np.linspace(0,1,6))

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

arange: [0 2 4 6 8]

linspace: [0.  0.2 0.4 0.6 0.8 1. ]


In [7]:
a = np.array([10,20,30,40])
b = np.array([2,4,5,8])
print('Addition:', a+b)
print('Subtraction:', a-b)
print('Multiplication:', a*b)
print('Division:', a/b)
print('Power:', a**2)
print('Square root:', np.sqrt(a))

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]
Power: [ 100  400  900 1600]
Square root: [3.16227766 4.47213595 5.47722558 6.32455532]


In [8]:
marks = np.array([65,72,81,90,56])
print('Original:', marks)
print('After +5 bonus:', marks+5)
print('Doubled:', marks*2)
print('Percentage:', marks/100*100)

Original: [65 72 81 90 56]
After +5 bonus: [70 77 86 95 61]
Doubled: [130 144 162 180 112]
Percentage: [65. 72. 81. 90. 56.]


In [9]:
marks = np.array([45,67,82,39,91,74,58])
print('Marks:', marks)
print('Pass condition:', marks >= 50)
print('Passed marks:', marks[marks >= 50])
print('Above 75:', marks[marks > 75])
print('Between 50 and 80:', marks[(marks >= 50) & (marks <= 80)])

Marks: [45 67 82 39 91 74 58]
Pass condition: [False  True  True False  True  True  True]
Passed marks: [67 82 91 74 58]
Above 75: [82 91]
Between 50 and 80: [67 74 58]


In [10]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
print('Add scalar 5:\n', data+5)
print('\nAdd [1,2,3] by column:\n', data+np.array([1,2,3]))
print('\nMultiply rows by [1,2,3]:\n', data*np.array([[1],[2],[3]]))

Add scalar 5:
 [[15 25 35]
 [45 55 65]
 [75 85 95]]

Add [1,2,3] by column:
 [[11 22 33]
 [41 52 63]
 [71 82 93]]

Multiply rows by [1,2,3]:
 [[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


In [11]:
data = np.array([12,18,25,30,22,15,28])
print('Data:', data)
print('Sum:', np.sum(data))
print('Mean:', np.mean(data))
print('Minimum:', np.min(data))
print('Maximum:', np.max(data))
print('Median:', np.median(data))

Data: [12 18 25 30 22 15 28]
Sum: 150
Mean: 21.428571428571427
Minimum: 12
Maximum: 30
Median: 22.0


In [12]:
scores = np.array([[70,80,90],[60,75,85],[88,92,78]])
print('Scores:\n', scores)
print('\nColumn sums:', np.sum(scores, axis=0))
print('Row sums:', np.sum(scores, axis=1))
print('Column means:', np.mean(scores, axis=0))
print('Row means:', np.mean(scores, axis=1))
print('Column minimums:', np.min(scores, axis=0))
print('Column maximums:', np.max(scores, axis=0))

Scores:
 [[70 80 90]
 [60 75 85]
 [88 92 78]]

Column sums: [218 247 253]
Row sums: [240 220 258]
Column means: [72.66666667 82.33333333 84.33333333]
Row means: [80.         73.33333333 86.        ]
Column minimums: [60 75 78]
Column maximums: [88 92 90]


In [13]:
student_marks = np.array([[78,85,92],[65,72,80],[90,88,95],[55,60,68],[82,79,85]])
print('Student marks:\n', student_marks)
totals = np.sum(student_marks, axis=1)
print('\nSubject means:', np.mean(student_marks, axis=0))
print('Student totals:', totals)
print('Overall mean:', np.mean(student_marks))
print('Highest mark:', np.max(student_marks))
print('Lowest mark:', np.min(student_marks))
print('Median:', np.median(student_marks))
print('Students with total >= 240:', totals[totals >= 240])

Student marks:
 [[78 85 92]
 [65 72 80]
 [90 88 95]
 [55 60 68]
 [82 79 85]]

Subject means: [74.  76.8 84. ]
Student totals: [255 217 273 183 246]
Overall mean: 78.26666666666667
Highest mark: 95
Lowest mark: 55
Median: 80.0
Students with total >= 240: [255 273 246]
